name: R Data Processing and Commit

on:
  push:
    branches: [main]
  schedule:
    # Weekdays only (1–5 = Mon–Fri)

    # DST: March–November
    # 7 AM ET = 11:00 UTC
    - cron: '0 11 * 3-11 1-5'
    # 3 PM ET = 19:00 UTC
    - cron: '0 19 * 3-11 1-5'

    # Standard Time: Jan, Feb, Dec
    # 7 AM ET = 12:00 UTC
    - cron: '0 12 * 1,2,12 1-5'
    # 3 PM ET = 20:00 UTC
    - cron: '0 20 * 1,2,12 1-5'

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # needed for pushing commits
          fetch-depth: 0  # fetch full history for rebase

      - name: Restore last processed cache
        id: cache-last-processed
        uses: actions/cache@v4
        with:
          path: tracker/data/last_processed.txt
          key: last-processed-file-${{ hashFiles('tracker/data/last_processed.txt') }}

      - name: Ensure last_processed.txt exists
        run: |
          mkdir -p tracker/data
          if [ ! -f tracker/data/last_processed.txt ]; then
            echo " " > tracker/data/last_processed.txt
          fi

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("dplyr","tidyr","here"), repos = "https://cloud.r-project.org")'

      - name: Run data processing script
        run: |
          Rscript data_processing.R

      - name: Save last processed file to cache
        if: always()
        uses: actions/cache@v4
        with:
          path: tracker/data/last_processed.txt
          key: last-processed-file-${{ hashFiles('tracker/data/last_processed.txt') }}

      - name: Commit and push updated files (rebase-safe)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git add tracker/data/app_data/*.rds tracker/data/total_data/*.rds tracker/data/diff_total/*.rds tracker/data/district_df/*.rds tracker/data/last_processed.txt
          git diff --cached --quiet || git commit -m "Daily data update $(date -u +'%Y-%m-%d')"
          git pull --rebase origin main
          git push
