name: R Data Processing and Commit

on:
  push:
    branches: [main]
  schedule:
    # Runs daily at 3:00 PM UTC
    - cron: '0 15 * * *'

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # needed for pushing commits

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("dplyr","tidyr","here"), repos = "https://cloud.r-project.org")'

      - name: Run data processing script
        run: |
          Rscript data_processing.R

      - name: Commit and push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tracker/data/app_data/*.rds tracker/data/total_data/*.rds tracker/data/diff_total/*.rds tracker/data/district_df/*.rds
          git diff --cached --quiet || git commit -m "Daily data update $(date -u +'%Y-%m-%d')"
          git push
