name: Deploy Shiny App

on:
  workflow_run:
    workflows: ["R Data Processing and Commit"]   # must exactly match Workflow B's name
    types:
      - success   # or 'completed' if you want it to run even if Workflow B fails


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install required R packages
        run: |
          Rscript -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_cran(c('curl', 'scales', 'shiny', 'dplyr', 'ggplot2', 'tidyr', 'lubridate', 'rsconnect','viridis'), dependencies = TRUE)"

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='${SHINYAPPS_NAME}', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"
          Rscript -e "rsconnect::deployApp(appDir = 'tracker', appName = 'nwri-tracker', forceUpdate = TRUE)"
