name: Daily Dropbox Download

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: /home/runner/work/_temp/Library

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Python + Dropbox SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install dropbox

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("reticulate", repos = "https://cloud.r-project.org")'
        env:
          R_LIBS_USER: ${{ env.R_LIBS_USER }}

      - name: Run R script
        run: Rscript dropbox_api.R
        env:
          R_LIBS_USER: ${{ env.R_LIBS_USER }}
